[package]
name = "llama-caller"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
