[package]
name = "todo-rest"
version = "0.1.0"
edition = "2024"

[dependencies]
todo-lib = { path = "../todo-lib" }
axum = "0.8.4"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.140"
