name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: todo-gui
            asset_name: todo-gui-linux
          - os: macos-latest
            artifact_name: todo-gui
            asset_name: todo-gui-macos
          - os: windows-latest
            artifact_name: todo-gui.exe
            asset_name: todo-gui-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Build Release
        run: cargo build --release --bin todo-gui

      - name: Rename binary
        shell: bash
        run: |
          cd target/release
          cp ${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
