name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write    # This is required for creating releases and uploading assets

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: todo-gui
            asset_name: todo-gui-linux
          - os: macos-latest
            artifact_name: todo-gui
            asset_name: todo-gui-macos

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Build Release
        run: |
          cd todo-gui
          cargo build --release --bin todo-gui

      - name: Rename binary
        shell: bash
        run: |
          cd todo-gui/target/release
          cp ${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Create Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${GITHUB_REF#refs/tags/} --notes "Release ${GITHUB_REF#refs/tags/}" --title "${GITHUB_REF#refs/tags/}"

      - name: Upload Release Asset
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${GITHUB_REF#refs/tags/} todo-gui/target/release/${{ matrix.asset_name }}
